sudo: false

language: node_js

node_js:
  - "4"
  - "6"
  - "8"
  - "10"

before_script:
  - npm install -g codecov

script:
  - npm run test
  - codecov

notifications:
  email:
    - vinta.chen@gmail.com
